In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import sys
import os

In [ ]:
# I will use the wine quality dataset
X = load_breast_cancer().data
y = load_breast_cancer().target

y = np.where(y == 0, -1, 1)

print(X.shape)
print(y.shape)

print(np.unique(y, return_counts = True ))

"""
There are 569 instances of data with 212 instances of class 0 and 357 instances of class 1.
There are 30 features.
"""
instances, features = X.shape

X_train , X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

(569, 30)
(569,)
(array([-1,  1]), array([212, 357]))


In [ ]:
class SVM:
  def __init__(self,
               learning_rate=0.001,
               lambda_param=0.01,
               n_iters=1000):

    # "Each class should have a constructor which initializes the weights and bias,"
    # ->> to initialize the weights and biases, the dimnensions should be known

    #instances, features = X.shape


    self.lr = learning_rate
    self.lambda_param = lambda_param

    self.n_iters = n_iters
    self.w = None
    self.b = None


  def forward(self, X_):

    print("inside forward function:\n X shape : ", X_.shape)
    print("X transpose shape : ", X_.transpose().shape)

    print("self.w shape : ", self.w.shape)
    print("self.b shape : ", self.b.shape)
    print("returning... " , ( X_.transpose() @ self.w) - self.b)
    #a function forward which computes the output of the ML model based on a given input
    return ( X_.transpose() @ self.w).item() - self.b

  #def hinge_loss(self, y, y_pred):
  #  return np.maximum( self.lambda_param * np.linalg.norm(self.w, ord=2) , self.lambda_param * np.linalg.norm(self.w, ord=2) + (1 - y * y_pred) )


  #def partial_derivative(self, y , y_pred)
  #  k = y.shape[0]


  def fit(  self, X, y):

    #print("---- in fit function")

    n_samples, n_features = X.shape

    #print("n_samples, n_features", n_samples, n_features)

    self.w = np.random.rand(n_features, 1)
    self.b = np.random.rand(1)


    print("self.w shape : ", self.w.shape)
    print("self.b shape : ", self.b.shape)

    y = np.where(y <= 0, -1, 1)

    #sys.exit(0)

    for _ in range(self.n_iters):
      for idx, x_i in enumerate(X): #


        x_i = x_i.reshape((-1, 1))
        print("--- in fit : x_i shape : ", x_i.shape)

        y_i_pred = self.forward(x_i)

        print("y_i_pred : ", y_i_pred)
        print("y_i_pred.shape" , y_i_pred.shape)
        #sys.exit(0)
        print(y_i_pred.shape)
        print(y[idx].shape)



        if (y[idx] * y_i_pred >= 1):
          self.w -= self.lr * (2 * self.lambda_param * self.w) # updating weight by a factor of regularization term
          self.b -= 0 # not updating the bias

        else: # penalize  the weight and bias  for making error wrt to the weight
          self.w -= self.lr * ( 2 * self.lambda_param * self.w - (x_i * y[idx]) ) # no bias was used in this eqn
          self.b -= self.lr * y[idx]

  def predict(self, X):
        return np.sign(np.dot(X, self.w) - self.b)


In [ ]:
# Example vector
v = np.array([3, 4])

# Calculate L2 norm
l2_norm = np.linalg.norm(v, ord=2)

print("L2 Norm of vector:", l2_norm)

L2 Norm of vector: 5.0


In [ ]:
# Set random seed for reproducibility
np.random.seed(0)

# Generate 6 samples for label +1
X_pos = np.random.rand(6, 3)  # 6 samples, 3 features
y_pos = np.ones(6)  # Label +1

# Generate 6 samples for label -1
X_neg = np.random.rand(6, 3)  # 6 samples, 3 features
y_neg = -np.ones(6)  # Label -1

# Combine positive and negative samples
X = np.vstack((X_pos, X_neg))  # Shape: (12, 3)
y = np.concatenate((y_pos, y_neg))  # Shape: (12,)

# Output the generated dataset
print("Input Features (X):")
print(X)
print("\nLabels (y):")
print(y)

Input Features (X):
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329]
 [0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033]
 [0.56843395 0.0187898  0.6176355 ]]

Labels (y):
[ 1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1.]


In [ ]:
# Initialize the SVM model
model = SVM(learning_rate=0.01, n_iters=10)

# Fit the model on the dataset
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Print results
print("Predictions:")
print(y_pred.flatten())
print("\nTrue Labels:")
print(y_test)
print("accuracy : ", accuracy_score(y_test, y_pred))

Streaming output truncated to the last 5000 lines.
y_i_pred :  [7977.7895632]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_i shape :  (30, 1)
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  [[-14961.61497774]]
y_i_pred :  [-14961.61497774]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_i shape :  (30, 1)
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  [[7310.42950784]]
y_i_pred :  [7310.42950784]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_i shape :  (30, 1)
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  [[8585.88702769]]
y_i_pred :  [8585.88702769]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_i shape :  (30, 1)
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  

In [ ]:
# Initialize the SVM model
model = SVM(learning_rate=0.01, n_iters=100)

# Fit the model on the dataset
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Print results
print("Predictions:")
print(y_pred.flatten())
print("\nTrue Labels:")
print(y_test)
print("accuracy : ", accuracy_score(y_test, y_pred))

Streaming output truncated to the last 5000 lines.
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  [[-15220.71203972]]
y_i_pred :  [-15220.71203972]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_i shape :  (30, 1)
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  [[7587.16483189]]
y_i_pred :  [7587.16483189]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_i shape :  (30, 1)
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  [[8964.32873898]]
y_i_pred :  [8964.32873898]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_i shape :  (30, 1)
inside forward function:
 X shape :  (30, 1)
X transpose shape :  (1, 30)
self.w shape :  (30, 1)
self.b shape :  (1,)
returning...  [[7810.41918278]]
y_i_pred :  [7810.41918278]
y_i_pred.shape (1,)
(1,)
()
--- in fit : x_

In [ ]:
# Initialize the SVM model
model = SVM(learning_rate=0.01, n_iters=1000)

# Fit the model on the dataset
model.fit(X, y)

# Make predictions
predictions = model.predict(X)

# Print results
print("Predictions:")
print(predictions.flatten())
print("\nTrue Labels:")
print("accuracy : ", accuracy_score(y, predictions))

In [ ]:
# Initialize the SVM model
model = SVM(learning_rate=0.01, n_iters=10000)

# Fit the model on the dataset
model.fit(X, y)

# Make predictions
predictions = model.predict(X)

# Print results
print("Predictions:")
print(predictions.flatten())
print("\nTrue Labels:")
print("accuracy : ", accuracy_score(y, predictions))